dist: focal
addons:
  apt:
    packages:
    - shellcheck

matrix:
  include:
    - language: bash
      install:
        - set -e
        - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip
        - unzip /tmp/terraform -d /tmp
        - chmod +x /tmp/terraform
        - /tmp/terraform -version
      script:
        - .ci/validate-terraform.sh
        - shellcheck salt/provision.sh
    - language: node_js
      install:
        - npm install -g jsonlint
      script:
        - git ls-files | grep '.json$' | xargs -I {} jsonlint -qc {}
    - language: python
      install:
        - pip install salt-lint
      script:
        - git ls-files | grep '.sls$' | xargs salt-lint

notifications:
  email: true
